# Generated by Django 5.2.7 on 2025-11-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0002_course_students_alter_course_instructors_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, null=True, verbose_name='Ders Syllabus'),
        ),
    ]
