# Generated by Django 5.2.7 on 2025-11-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0003_alter_course_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='course_syllabus/', verbose_name='Ders Syllabus Dosyası (.pdf, .docx vb.)'),
        ),
    ]
