# Generated by Django 5.2.7 on 2025-11-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0004_alter_course_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Çıktı Kodu (örn: PO-1)')),
                ('description', models.TextField(verbose_name='Program Çıktısı Açıklaması')),
            ],
            options={
                'verbose_name': 'Program Çıktısı',
                'verbose_name_plural': 'Program Çıktıları',
                'ordering': ['code'],
            },
        ),
    ]
